/***********************************************************************/
/*                                                                     */
/*  FILE        :trap_2.c                                              */
/*  DATE        :Wed, Oct 25, 2006                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :SH7709S                                               */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.3.1).     */
/*                                                                     */
/***********************************************************************/
                  


#ifdef __cplusplus
//#include <ios>					// Remove the comment when you use ios                  
//int ios_base::Init::init_cnt;		// Remove the comment when you use ios
#endif
#ifdef __cplusplus
extern "C" {
#endif
void abort(void);
#ifdef __cplusplus
}
#endif

#include "7709s.h"
#include "math.h"

#define LED_DATA (*(volatile unsigned short *)0x00800000) /* LED   Address*/

void LED_FLASH(void);

int i,k,Light,j;

/////////////////////////////////////////////////////////////////////////////

void LED_FLASH(void)
{
	LED_DATA=0x55;
	for(j=0;j<3600;j++)
	{
		Light=255;
		Light=sin(j/180.0*3.1416)*255;
		for(i=0;i<0x100000;i++){}
		LED_DATA = Light;
		for(i=0;i<0x100000;i++){}
		LED_DATA = Light;
	}
}

#pragma interrupt(INT_TRAPA)
void INT_TRAPA(void)
{
	LED_FLASH();
}

void main(void)
{
	while(1)
	{
		trasm();
	}
}

void abort(void)
{
	
}