/***********************************************************************/
/*                                                                     */
/*  FILE        :resetprg.c                                            */
/*  DATE        :Wed, Apr 20, 2005                                     */
/*  DESCRIPTION :Reset Program                                         */
/*  CPU TYPE    :SH7709S                                               */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.3.1).     */
/*                                                                     */
/***********************************************************************/
                  
#include	<machine.h>
#include	<_h_c_lib.h>
//#include	<stddef.h>					// Remove the comment when you use errno
//#include 	<stdlib.h>					// Remove the comment when you use rand()
#include	"stacksct.h"
#include 	"7709S.H"

#define SR_Init    0x40000000			//此行为重新定义，使用默认运行不了
//#define SR_Init    0x000000F0
#define SR_IntOFF  0x7fffffff
#define INT_OFFSET 0x100UL
#define LED_DATA (*(volatile unsigned short *)0x00800000) 

extern void INTHandlerPRG(void);
extern void PowerON_Reset_PC(void);
extern void main(void);

//#ifdef __cplusplus				// Use SIM I/O
//extern "C" {
//#endif
//extern void _INIT_IOLIB(void);
//extern void _CLOSEALL(void);
//#ifdef __cplusplus
//}
//#endif

#pragma section ResetPRG
#pragma entry PowerON_Reset
void PowerON_Reset(void)
{ 
    set_vbr((void *)((unsigned int)INTHandlerPRG - INT_OFFSET));
	_INITSCT();
	set_cr(SR_Init);					//初始化为特权模式，或者将本行注释掉均可正常运行，因复位自动初始化为特权模式
    nop();	
	main();
	sleep();
}

//#pragma entry Manual_Reset			// Remove the comment when you use Manual Reset
void Manual_Reset(void)	
{
} 

