/***********************************************************************/
/*                                                                     */
/*  FILE        :stacksct.h                                            */
/*  DATE        :Thu, Nov 23, 2006                                     */
/*  DESCRIPTION :Setting of Stack area                                 */
/*  CPU TYPE    :SH7709S                                               */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.3.1).     */
/*                                                                     */
/***********************************************************************/
#pragma stacksize 0x400         /* Do not modify this line. */
